FROM nginx:1.27-alpine

RUN apk add --no-cache apache2-utils

COPY nginx.conf /tmp/default.conf
COPY docker-entrypoint.d/10-create-htpasswd.sh /docker-entrypoint.d/10-create-htpasswd.sh

RUN mkdir -p /etc/nginx/auth \
    && cat /tmp/default.conf > /etc/nginx/conf.d/default.conf \
    && chown root:root /etc/nginx/conf.d/default.conf \
    && chmod 644 /etc/nginx/conf.d/default.conf \
    && chmod 755 /docker-entrypoint.d/10-create-htpasswd.sh \
    && rm -f /tmp/default.conf
